### ISSUE TITLE
Constantly switching the name of the browser tab

### ISSUE THREAD

**Issue by rikardn** [pharmpy/modelbuilder#11]
When running the app the tab in the browser will be constantly toggling between being named "Pharmpy GUI" and "Updating...". I am using Firefox. In chrome it doesn't switch back and forth but is stable on "Pharmpy GUI"

**Comment by rikardn** [comment]
When opening other tabs and switching between tabs in Chrome it also changes the name of the tab to "Updating..." briefly.

**Comment by davsjob** [comment]
Fixed! :)
