### ISSUE TITLE
Strange default variability for 1P model

### ISSUE THREAD

**Issue by rikardn** [pharmpy/modelbuilder#118]
If setting 1 peripheral and going to the parameter variability tab there is no variability on any parameter. CL and VC should still be the default.

**Comment by antoniaih** [comment]
At the moment the variability is reset when changing anything in the structural tab because for some changes the parameters change and then the model can be treated as a new model. But for the peripherals this does not make sense. I will change this.

**Comment by antoniaih** [comment]
Fixed in 8b40f80
