### ISSUE TITLE
Hard to distinguish between labels and buttons

### ISSUE THREAD

**Issue by rikardn** [pharmpy/modelbuilder#12]
For example after starting the app: "Model Type" and "Model format" are labels and "Write model" and "Choose dataset" are buttons, but they look exactly the same (perhaps the font is slightly different). I think it should be possible to know what is clickable just by looking.

**Comment by davsjob** [comment]
Good note!
Suggestion is to keep color on the labels as headers but make buttons in their complementary color. 
Another option is to keep the color of one and make the other more anonymous

**Comment by davsjob** [comment]
Changed the colors in the latest update! Info-blue for buttons and green for headers!
