### ISSUE TITLE
Unclear name of starting model

### ISSUE THREAD

**Issue by rikardn** [pharmpy/modelbuilder#122]
When first opening the UI the "Name" field is empty, but when generating Python code the name is "start". We should either have a starting name in the "Name" field or not set a name in the Python code.

**Comment by antoniaih** [comment]
fixed in https://github.com/pharmpy/modelbuilder/commit/1e17bba9b203b6f9f38981c8d381427ea2c3b019

**Comment by rikardn** [comment]
Nice. I have tested and it works now
