### ISSUE TITLE
Confusing "convert_model" in generated code

### ISSUE THREAD

**Issue by rikardn** [pharmpy/modelbuilder#123]
The target for the `convert_model` call in the generated code is confusing. It seems to originate from the latest model type you used. Not sure how we can solve this. Ideas?

**Comment by antoniaih** [comment]
I think it makes sense to have it like that. I imagine a user builds e.g. a NONMEM model and then wants to see the code to generate that model. Otherwise we could display something like `<model_format>` to indicate that this has to be filled in manually by the user.

**Comment by rikardn** [comment]
The problem is that the radio buttons for the format becomes dependent on the order of clicking them, which seems counter intuitive. But I agree that it is hard to see a good alternative. Let us keep this open and think a bit more.

**Comment by antoniaih** [comment]
Layout was updated to include tabs for switching between model view and code view.

**Comment by rikardn** [comment]
Nice!
