### ISSUE TITLE
Crash when selecting transits

### ISSUE THREAD

**Issue by rikardn** [pharmpy/modelbuilder#124]
Way to reproduce:

* Click Oral
* Go to structural tab
* Click transits

Now there is an error message

**Comment by antoniaih** [comment]
I think this is due to a change in pharmpy which has not been released yet. See  commit: https://github.com/pharmpy/pharmpy/commit/493e56fe191980e5b1d8946d30540aac5da24067

**Comment by rikardn** [comment]
Ok, so it is a bug in the released version of Pharmpy that we have now fixed.

**Comment by antoniaih** [comment]
Fixed with new Pharmpy release
