### ISSUE TITLE
Clickable area of tabs of code type to the left is too small

### ISSUE THREAD

**Issue by rikardn** [pharmpy/modelbuilder#126]
In both firefox and Chrome there is a narrow clickable field at the top of the tabs above the text.

**Comment by antoniaih** [comment]
Fixed in https://github.com/pharmpy/modelbuilder/commit/062bebdc09ad8e3956c0ffb7378aa46da4972633

**Comment by rikardn** [comment]
It is better, but from half the text down it is still unclickable for me.

**Comment by antoniaih** [comment]
Fixed in https://github.com/pharmpy/modelbuilder/commit/34225946c20da4835d35150b3613349d26a17d98

**Comment by rikardn** [comment]
Thanks. It works now
