### ISSUE TITLE
Only get non-covariate columns in covariate table

### ISSUE THREAD

**Issue by rikardn** [pharmpy/modelbuilder#127]
I added the pheno dataset on wanted to add a covariate effect. In the drop down of the "Covariate" column I got all columns except the covariates. I.e. I got ID, DV, TIME and AMT.

**Comment by antoniaih** [comment]
Fixed in https://github.com/pharmpy/modelbuilder/commit/d442f77a2fa39870b7e70becaf0056605bdddac7

**Comment by rikardn** [comment]
Now all columns get shown. Perhaps even better would be to only show columns with `unknown` or `covariate` types.

**Comment by antoniaih** [comment]
Fixed in https://github.com/pharmpy/modelbuilder/commit/3e53bb05896368428531ca3cadfbcaee6911440d

**Comment by rikardn** [comment]
I've tested the fix and can confirm that the issue is now resolved. Closing this issue.
