### ISSUE TITLE
Dataset widget is outside screen

### ISSUE THREAD

**Issue by rikardn** [pharmpy/modelbuilder#132]
This is a recent regression. The dataset widget is partially too far down to be seen. This worked earlier today

**Comment by rikardn** [comment]
It could be that the Model/Python/R tabs are now larger?

**Comment by rikardn** [comment]
This is what it looks like at the bottom of my screen. The dataset widget used to fit fine, but now I have to scroll.

![image](https://github.com/user-attachments/assets/fa567b46-528c-432c-8b3d-c769f8a73850)

**Comment by antoniaih** [comment]
Yes, because of the bigger tabs the dataset widget is a bit further down. I can make the text area shorter but depending on the scaling in the browser the widget might still be outside the window without scrolling.

**Comment by antoniaih** [comment]
Update in https://github.com/pharmpy/modelbuilder/commit/34225946c20da4835d35150b3613349d26a17d98

**Comment by rikardn** [comment]
This works on my computer now. At least when having maximized the browser.
