### ISSUE TITLE
Cannot change name of parameter

### ISSUE THREAD

**Issue by rikardn** [pharmpy/modelbuilder#21]
If I try to change the name of "POP_CL" in the starting model I get a crash and the name of the parameter is not changed

**Comment by davsjob** [comment]
One way to prevent this would be to make the name of a parameter unchangeable, and if a user would like to change the name of a parameter they would then have to remove it and then add it again.

**Comment by rikardn** [comment]
Couldn't we make the names changeable?

**Comment by davsjob** [comment]
I think so, the suggested solution would in that case be a temporary fix that prevents the crash while keeping the functionality.
