### ISSUE TITLE
Changes in parameters stopped working

### ISSUE THREAD

**Issue by davsjob** [pharmpy/modelbuilder#27]
When editing values in the parameter table, it does not update accordingly

**Comment by davsjob** [comment]
This only applies if you go directly from base-tab to parameter-tab, and the error raised is:
```
raise TypeError("Cannot validate parameters since all are not numeric")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by rikardn** [comment]
Interesting. Might be a bug in Pharmpy. Any way of reproducing with plain function calls?

**Comment by davsjob** [comment]
I have found the origin of the bug, it was mainly due to callback structure so nothing in Pharmpy. 
I will solve it and send a PR soon.
