### ISSUE TITLE
Change from generic model to nonmem model does not work

### ISSUE THREAD

**Issue by antoniaih** [pharmpy/modelbuilder#30]
When changing from generic model format to nonmem model format after having changed the iiv of some parameters the code is not nonmem code anymore:

The nonmem code looks as follows:
`{"parameters": {"parameters": [{"name": "POP_CL", "init": 0.01, "lower": 0, "upper": null, "fix": false}, {"name": "POP_VC", "init": 1, "lower": 0, "upper": null, "fix": false}, {"name": "IIV_CL", "init": 0.1, "lower": null, "upper": null, "fix": false}, {"name": "IIV_VC", "init": 0.1, "lower": null, "upper": null, "fix": false}, {"name": "IIV_CL_IIV_CL", "init": 0.01, "lower": -Infinity, "upper": Infinity, "fix": false}, {"name": "sigma", "init": 0.09, "lower": -Infinity, "upper": Infinity, "fix": false}]}, "random_variables": {"dists": [{"class": "JointNormalDistribution", "names": ["ETA_CL", "ETA_VC"], "level": "IIV", "mean": "MutableDenseMatrix([[Integer(0)], [Integer(0)]])", "variance": "MutableDenseMatrix([[Symbol('IIV_CL'), Symbol('IIV_CL_IIV_CL')], [Symbol('IIV_CL_IIV_CL'), Symbol('IIV_VC')]])"}, {"class": "NormalDistribution", "name": "epsilon_p", "level": "RUV", "mean": "Integer(0)", "variance": "Symbol('sigma')"}], "eta_levels": {"levels": [{"name": "IIV", "reference": true, "group": "ID"}, {"name": "IOV", "reference": false, "group": "OCC"}]}, "epsilon_levels": {"levels": [{"name": "RUV", "reference": true, "group": null}]}}, "statements": {"statements": [{"class": "Assignment", "symbol": "Symbol('CL')", "expression": "Mul(Symbol('POP_CL'), exp(Symbol('ETA_CL')))"}, {"class": "Assignment", "symbol": "Symbol('VC')", "expression": "Mul(Symbol('POP_VC'), exp(Symbol('ETA_VC')))"}, {"class": "CompartmentalSystem", "compartments": [{"class": "Output"}, {"class": "Compartment", "name": "CENTRAL", "amount": "Symbol('A_CENTRAL')", "dose": {"class": "Bolus", "amount": "Symbol('AMT')", "admid": 1}, "input": "Integer(0)", "lag_time": "Integer(0)", "bioavailability": "Integer(1)"}], "rates": [[1, 0, "Mul(Symbol('CL'), Pow(Symbol('VC'), Integer(-1)))"]], "t": "Symbol('t')"}, {"class": "Assignment", "symbol": "Symbol('IPRED')", "expression": "Mul(Symbol('A_CENTRAL'), Pow(Symbol('VC'), Integer(-1)))"}, {"class": "Assignment", "symbol": "Symbol('IPREDADJ')", "expression": "Piecewise(ExprCondPair(Float('2.2250000000000002e-16', precision=53), Equality(Symbol('IPRED'), Integer(0))), ExprCondPair(Symbol('IPRED'), true))"}, {"class": "Assignment", "symbol": "Symbol('IPREDADJ1')", "expression": "Piecewise(ExprCondPair(Float('2.2250000000000002e-16', precision=53), Equality(Symbol('IPRED'), Integer(0))), ExprCondPair(Symbol('IPRED'), true))"}, {"class": "Assignment", "symbol": "Symbol('Y')", "expression": "Add(Symbol('IPRED'), Mul(Symbol('IPREDADJ1'), Symbol('epsilon_p')))"}]}, "estimation_steps": {"steps": [{"method": "FOCE", "interaction": true, "cov": null, "evaluation": false, "maximum_evaluations": 99999, "laplace": false, "isample": null, "niter": null, "auto": null, "keep_every_nth_iter": null, "solver": null, "solver_rtol": null, "solver_atol": null, "tool_options": {}}]}, "datainfo": {"columns": [{"name": "ID", "type": "id", "scale": "nominal", "continuous": false, "categories": null, "unit": "1", "datatype": "int32", "drop": false, "descriptor": null}, {"name": "TIME", "type": "idv", "scale": "ratio", "continuous": true, "categories": null, "unit": "1", "datatype": "float64", "drop": false, "descriptor": null}, {"name": "DV", "type": "dv", "scale": "ratio", "continuous": true, "categories": null, "unit": "1", "datatype": "float64", "drop": false, "descriptor": null}, {"name": "AMT", "type": "dose", "scale": "ratio", "continuous": true, "categories": null, "unit": "1", "datatype": "float64", "drop": false, "descriptor": null}, {"name": "DVID", "type": "unknown", "scale": "ratio", "continuous": true, "categories": null, "unit": "1", "datatype": "float64", "drop": false, "descriptor": null}], "path": null, "separator": "\\s+"}, "value_type": "PREDICTION", "dependent_variables": {"Y": 1}, "observation_transformation": {"Symbol('Y')": "Symbol('Y')"}, "initial_individual_estimates": null, "__magic__": "Pharmpy Model", "__version__": "0.99.0"}`

**Comment by davsjob** [comment]
Thank you, will look into it! The format you see what is returned from `get_model_code(model)` if the format of the model is generic.
Maybe it crashes somewhere when changing the IIVs.
Do you get a error code or is the model still running?

**Comment by antoniaih** [comment]
I get this error message:

```
Traceback (most recent call last):
  File "/home/antonia/pharmpy_gui/modelbuilder/app.py", line 114, in change_format
    globals()["model"] = convert_model(globals()["model"], format)
  File "/home/antonia/pharmpy_gui/pharmpy_ui/lib/python3.10/site-packages/pharmpy/modeling/common.py", line 172, in convert_model
    new = module.convert_model(model)
  File "/home/antonia/pharmpy_gui/pharmpy_ui/lib/python3.10/site-packages/pharmpy/model/external/nonmem/model.py", line 108, in convert_model
    nm_model = nm_model.update_source()
  File "/home/antonia/pharmpy_gui/pharmpy_ui/lib/python3.10/site-packages/pharmpy/model/external/nonmem/model.py", line 166, in update_source
    control_stream = update_thetas(
  File "/home/antonia/pharmpy_gui/pharmpy_ui/lib/python3.10/site-packages/pharmpy/model/external/nonmem/update.py", line 112, in update_thetas
    new = create_theta_record(param)
  File "/home/antonia/pharmpy_gui/pharmpy_ui/lib/python3.10/site-packages/pharmpy/model/external/nonmem/update.py", line 278, in create_theta_record
    if upper < 1000000:
TypeError: '<' not supported between instances of 'NoneType' and 'int'
```

**Comment by rikardn** [comment]
This does not crash any longer.
