### ISSUE TITLE
Change to check boxes in model covariance matrix

### ISSUE THREAD

**Issue by JohanWBorg** [pharmpy/modelbuilder#67]
Should automatically check the corresponding symmetry

**Comment by JohanWBorg** [comment]
After cc875d, the values in the matrix are changed to "X". We want to be able to use checkboxes, but this is not implemented in dash yet. Possible workarounds could be to change cell if currently being selected, but this comes with flaws as well.

**Comment by rikardn** [comment]
I think it is close enough now.
